In [3]:
import tensorflow as tf # When we import TensorFlow, a default graph is made

hello = tf.constant("Hello, TensorFlow!") # Add a constant-operation to the (default) graph

print(hello.numpy())


b'Hello, TensorFlow!'


In [4]:
a = tf.constant(3.0)
b = tf.constant(4.0)
sum = tf.add(a,b)

print(sum.numpy())

7.0


In [8]:
x = tf.constant([[1,6],[3,4]])
y = tf.constant([[1],[2]])

product = tf.matmul(x,y)
print(product.numpy())

[[13]
 [11]]


In [8]:
import tensorflow as tf
import numpy as np

x = tf.constant([[1.0], [2.0]], dtype=tf.float32)
W = tf.constant([[3.0, 4.0], [5.0, 6.0]], dtype=tf.float32)
y = tf.matmul(W, x)

print("x is [[1.0], [2.0]]:")
print(y.numpy())

x = tf.constant([[2.0], [4.0]], dtype=tf.float32)
y = tf.matmul(W, x)

print("x is [[2.0], [4.0]]:")
print(y.numpy())


x is [[1.0], [2.0]]:
[[11.]
 [17.]]
x is [[2.0], [4.0]]:
[[22.]
 [34.]]


In [18]:
x = tf.constant([[1.0],[2.0]], dtype = tf.float32)
rand = tf.random.normal(shape = [2,2])
y = tf.Variable(rand)
z = tf.matmul(y, x)

print("The random matrix is:\n ")
print(y.numpy())

print("The product matrix is:\n")
print(z.numpy())

The random matrix is:
 
[[ 0.2614007  -1.379482  ]
 [-1.3887718  -0.45864195]]
The product matrix is:

[[-2.4975634]
 [-2.3060555]]


In [22]:
x = tf.constant([[1.0],[2.0]])
y = tf.Variable(tf.random.normal(shape = [2,2])) # we initialize y with the random variable instead
z = tf.matmul(y, x)

print("Random values initialized to y:\n")
print(y.numpy())
print("Product matrix:\n")
print(z.numpy())

[[-1.4426864   0.5026594 ]
 [-1.0265445  -0.24603954]]
[[-0.43736768]
 [-1.5186236 ]]
